### PR TITLE
Add option to suppress status messages

### PR DESCRIPTION
**Pull request by rconde01**
Useful for when you only want output generated when a leak is detected

### CODE REVIEW

**Comment by rconde01** [comment]
Arkady...can you comment on this pr? Are you against the idea or the implementation?

**Comment by KindDragon** [comment]
Sorry, was busy on one big PR. Can you fix conflicts and rebase?

**Comment by rconde01** [comment]
Sure thing

**Comment by KindDragon** [comment]
Fill free to reopen the issue when you fix conflicts

**Pull request closed without merging**
