### PR TITLE
rebased ioannise PR

### PR DESCRIPTION
**Pull request by Trass3r**
https://vld.codeplex.com/SourceControl/network/forks/ioannise/vld/contribution/8453
rebased it to current master to fix https://vld.codeplex.com/workitem/9519

Otherwise it's impossible to use vld with Qt or any other framework using file open dialogs.
Tested with VS2015 x64 on Windows 7.

### CODE REVIEW

**Comment by KindDragon** [comment]
Sorry. Can't accept it. Almost all test dosn't work

**Comment by Trass3r** [comment]
Question is why.
I don't see compilation errors, only "Build execution time has reached the maximum allowed time for your plan (40 minutes)." hidden in the messages tab and some "The system cannot find the path specified"
https://ci.appveyor.com/project/KindDragon/vld/build/61/job/9oo19keut0dlbihk/messages

**Comment by ioannis-e** [comment]
@Trass3r and @KindDragon, I have updated today my fork and PR on codeplex (PR shows more commits for some reason).

I would suggest to use the latest version as i cleaned up some code and fixed some bugs in my code.
I tested my latest work on VS2013 and 2015 fully with all tests PASSING
VS2010 had some issues compiling debug versions regarding _ITERATOR_DEBUG_LEVEL

The way the tests were run were to "Batch Build..." everything, then run the following
```
runalltests.bat v120
```
or
```
runalltests.bat v140
```

@KindDragon if you are interested we can discuss the commits here, on codeplex or on irc in order to identify what you like and don't like and cherry pick as much as possible into the master, in order to resolve some long standing issues.

**Comment by ioannis-e** [comment]
I am running appveyor now and i realised i changed the configuration name in vs14 (to be consistent accross VS versions) which causes build failure.

I will revert that change by force push and run appveyor again.

**Comment by Trass3r** [comment]
@ioannis-e even better! Hope it will be upstream soon.

**Comment by ioannis-e** [comment]
[Appveyor Success](https://ci.appveyor.com/project/ioannis-e/vld/build/3)
Now we need to review and discuss any performance optimazations

**Comment by KindDragon** [comment]
@ioannis-e please create PR on GitHub to discuss further and check Appveyor status

**Pull request closed without merging**
